# Site settings
title: Kobe Martin
email: kobe@kobemartin.com
description: > # this means to ignore newlines until "baseurl:"
  I am a PhD student in the Rogers Lab at the University of New South Wales. My research largely focuses on the evolution of acoustic communication in mammals.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kobemartin.com/" # the base hostname & protocol for your site
github_username:  kobes21
linkedin_username: kobe-martin

# Build settings
markdown: kramdown

# Colections
collections:
  events:
    output: true
  publications:
    output: true
  research:
    output: true
